### ISSUE TITLE
Bintray Download for 6.1.0 down

### ISSUE THREAD

**Issue by NHollmann** [playframework/play-ebean#216]
As we had some problems very similar to #214 we updated play-ebean to 6.1.0-RC3 with the following line in `plugins.sbt`:
`addSbtPlugin("com.typesafe.sbt" % "sbt-play-ebean" % "6.1.0-RC3")`

This worked fine but today I experimented with building in a docker container and then got the exception that play-ebean couldn't be loaded as `https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.13/6.1.0-RC3/play-ebean_2.13-6.1.0-RC3.pom` returned a 403. And in fact, the complete artifact directory at https://dl.bintray.com/playframework/maven/com/typesafe/play/play-ebean_2.13/6.1.0-RC3 returns a 403. 

I'm not enough into maven, bintray etc. so this is purely a speculation but could this be related to the [bintray sunset](https://www.jfrog.com/confluence/display/BT/Welcome+to+JFrog+Bintray)? According to this link the community central was shut down on May 1st. But maybe this ist just temporary, I don't know.

It looks like the 6.0.0 is hosted directly on maven central so it isn't affected. But as the ebean version changed I fear that downgrading would produce a lot of errors in my project, so is there a way to set a mirror for downloading play-ebean? Or could a contributor move the artifacts away from bintray?

**Comment by felipebonezi** [comment]
@mkurz @octonato help guys, everybody is having the same problem!
Bintray is down (btw, I think Bintray was discontinued) ⚠️

**Comment by octonato** [comment]
yes, that's because of the bintray sunset. 

This project is being mainly managed by the community. We (lightbend) take cares for the signing for publishing though. 

@NHollmann / @felipebonezi, would one of you be able to send a PR to fix it? 
Maybe @jmswenski or @lapidus79 can give some help? 

If you need an example, you can check that other PR from play-json.
https://github.com/playframework/play-json/pull/603/files

If changes the publishing to use `sbt-ci-release`. The same needs to be done here. 

Once the PR is out, I can add the credentials to travis in order to the the artefacts signed and published to sonatype.

**Comment by felipebonezi** [comment]
@octonato I've forked and will try fix it.

**Comment by GithubUser8080** [comment]
Any news on this? I am unable to download version 6.1.0 using sbt
