### ISSUE TITLE
Where can I download 6.1.0 from?

### ISSUE THREAD

**Issue by geo-m** [playframework/play-ebean#221]
The plugin version is listed in the README but it is not available anywhere

**Comment by almothafar** [comment]
From the internet they said, there is no answer for this, this question is there for a few months in #208

**Comment by felipebonezi** [comment]
It will be fixed with #222

**Comment by franzgranlund** [comment]
Is there any status update for this? Is there a chance that it may be releases sometime?

**Comment by mkurz** [comment]
I am happy to chip in and fix play-ebean, however that won't happen in december. If you want to support me, please consider donating to our collective: https://www.playframework.com/sponsors

**Comment by mkurz** [comment]
play-ebean 6.2.0-RC4 released, please have a look at the release notes how to upgrade: https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC4. Please test and let us know if it works for you, thanks!

**Comment by mkurz** [comment]
@franzgranlund I am pretty sure you have form classes which have `public` fields. play-enhancer added getter and setter methods for such fields. To bind and validate request parameters to a form class setters are needed by default. However, play-ebean 6.2.0-RC4 removed play-enhancer, so there are no setters generated anymore. That is why you get such an exception.
Solution:
* Either add getters and setter to all your form classes (and probably make the `public` field `private` instead)
* Or instead you can also just set `play.forms.binding.directFieldAccess = true` in `conf/application.conf`, without the need of changing code.

You can find more information here: https://www.playframework.com/documentation/2.8.x/JavaForms#Defining-a-form

> As you can see, by default, you have to define getter and setter methods so Play is able to access the Form fields. You can however also enable “direct field access” (for all forms) by setting `play.forms.binding.directFieldAccess = true` in `conf/application.conf`. In this mode Play will ignore the getter and setter methods and will try to directly access the fields

**Comment by franzgranlund** [comment]
@mkurz Thank you. You are correct, I have form classes with public fields. Your solution by adding `play.forms.binding.directFieldAccess = true` did the trick for my forms. However, now my Ebean models won't lazy load automatically when using fields annotated with @ManyToOne (I'm also using public fields for my models, as shown in earlier Play Framework 2.6 Ebean examples). Is this also due to not play-enhancer being included in 6.2.0-RC4 or has it to do with the new Ebean version? Is there any setting I could use to enable that again?

**Comment by mkurz** [comment]
@franzgranlund ebean got upgraded in RC4, so that might be the reason. The thing that changed by removing the play-enhancer is that there aren't getters and setters generated, so you could try to just add them to your public fields yourself (your IDE will help you to generate code) and see if lazy loading works again (if so then ebean needs those getters/setters for lazy loading to work). I am not really familiar with ebean since I never used it.

**Comment by franzgranlund** [comment]
@mkurz Yes, you are correct. I tested and Ebean needs getters and setters to work with lazy loading. I guess that this worked before since the play-enhancer was included in earlier play-ebean. 

It is quite easy to start using getters and setters I guess, and my IDE will help me, no problem. But just out of curiosity, why was play-enhancer removed and can I myself add it? 

I think it would be a good idea to clarify in the README that the play-enhancer is removed in this version of play-ebean.

**Comment by PromanSEW** [comment]
@franzgranlund I got same error with JSR, also problem with public fields ( #228 )

**Comment by mkurz** [comment]
> But just out of curiosity, why was play-enhancer removed and can I myself add it?

It was decided by Lightbend in May 2020 to archive repos they don't see a future in, like [play-enhancer](https://github.com/playframework/play-enhancer). I think there are problems with Java 11 as well. Not sure how hard it would be to support newer Java versions.
In theory, if someone wants to maintaintain the library _on a regular basis_ we could again bring it to life again, however I don't see much sense in it. What play-enhancer did was too much magic IMHO and there are very popular libraries out there (e.g. Lombok) which provide you [the same functionality anyway](https://projectlombok.org/features/GetterSetter). Also with the new [record](https://openjdk.java.net/jeps/395) types in newer Java versions getter/setter enhancing might not be needed anymore.


FYI: I updated the [release notes](https://github.com/playframework/play-ebean/releases/tag/6.2.0-RC4) with notes about the problems you experienced and linked them in the [README](https://github.com/playframework/play-ebean) as well.
