### ISSUE TITLE
Play Ebean dependency for DI (play2.4.x)

### ISSUE THREAD

**Issue by pycloux** [playframework/play-ebean#51]
Hi,
I am facing an issue with my DI configuration.
I need to access the database in my singleton "at initialization".
What is the dependency which I should set to ensure that Ebean is activated "before" my singleton is injected by Guice ?
Regards,
PYC

**Comment by pycloux** [comment]
Here is an update.
I created a component which using a dependency on EbeanConfig and registers a default EbeanServer in its constructor.
Then I ensure that the components using Ebean depends on this component.
It seems to solve the issue.
Not sure it is the best option.

**Comment by justinnichols** [comment]
@pycloux would you mind posting an example of your workaround with code?  I'm running into the same issue.  Basically I have a timing problem where Ebean is not quite done at the time I need to use it with my module.

**Comment by jroper** [comment]
All you need to do is declare a dependency on `play.db.ebean.EbeanConfig`.

**Comment by justinnichols** [comment]
I determined that at some point yesterday by doing this in one of my `@Singleton` components:

`@Inject
    public CustomComponentImpl(Configuration configuration, EbeanConfig ebeanConfig) {
        super(configuration, ebeanConfig);
    }`

The problem is that even when doing this, the following code still produces a timing issue problem that results in the error `Caused by: java.lang.RuntimeException: DataSource user is null?`:

`this.datasource = configuration.getString("datasource.name");
this.db = Ebean.getServer(this.datasource);`

**Comment by justinnichols** [comment]
So it turns out it's not enough to just wait for `EbeanConfig`.  You also have to wait for `DynamicEvolutions`.  This seemed to work without fail:

```
@Inject
public CustomComponentImpl(Configuration configuration, DynamicEvolutions dynamicEvolutions, EbeanConfig ebeanConfig) {
     super(configuration, ebeanConfig);
}
```

**Comment by pycloux** [comment]
Hi All,

Sorry for the late answer.
Actually I had to do a lot more because of the fact that Ebean startup and shutdown is happening independently from the dependency injection.

First I disabled the Ebean module in my configuration file:
```
play.modules.disabled += "play.db.ebean.EbeanModule"
```
The I created an injectable component (which I register in my own module) which is requested by the modules which depends on the database.

Within this module, I am dealing myself with the EBean server start (and stop):
```
    /**
     * Initialize the database (by running patches if required)
     */
    private void init(Configuration configuration) {
        // Register the Ebean server as the default one
        ServerConfig serverConfig = getEbeanConfig().serverConfigs().get(getEbeanServerDefaultName());
        Ebean.register(EbeanServerFactory.create(serverConfig), true);
    }
```

This solve the "startup" issue.
But you'll notice that by default, Ebean registers a "shutdown hook".
This means that it stops as soon as you ask the application to stop.
This was causing some issues in our application since the shutdown was happening completely independently of the injection order. So sometime the Ebean was shutdown while some components needed it to be up.

For this last challenge, please see https://github.com/ebean-orm/avaje-ebeanorm/issues/427

**Comment by justinnichols** [comment]
Thanks @pycloux !  I will see if I run into the same kinds of issues.  Presently the only issue I have (which may be related to what you posted) is that the above `CustomComponentImpl` I suggested doesn't wait for evolutions to complete (even though it waits for the DynamicEvolutions component to be ready).  Therefore, when my module starts, it isn't waiting for the evolutions to be completed (even with autoApply set to true) which will cause the module to fail starting (since an eagerly() bound component attempts to use Ebean and the database).
