### ISSUE TITLE
Support ebean 8.x

### ISSUE THREAD

**Issue by dhirenpratap** [playframework/play-ebean#91]
As ebean is into 8.x (refer: https://github.com/ebean-orm/ebean/releases) and agent has been changed to 8.x as well. What is the plan for the upgrade.

**Comment by marcospereira** [comment]
Hey @dhirenpratap,

I'm not sure if Ebean 8.x is compatible with the current version used by play-ebean, but looking at the release notes, the upgrade should be pretty straightforward.

Do you want to submit a pull request doing that?

**Comment by PierreAdam** [comment]
Hello, @marcospereira 

Currently you can only go for the 8.1.1. Any version higher would not work as the groupId and artefactId has changed. So you basically can't force SBT to replace the library.

So right now a change within PlayFramework looks like the only choice for the future.

Removing the Ebean (1.7.6) as dependency from Play so that we would be able to choose the Ebean version would be a good idea in my mind. But i'm sure there were initial reason for this dependence.

**Comment by 0xbaadf00d** [comment]
@marcospereira I can propose a PR within few days. If you want, I can do this in two times :

1. I propose a PR to upgrade to Ebean 7.21.3 who don't break anything on your current code

2. You create a develop branch on your repository and a propose a new PR for Ebean 8.x into this new "develop" branch

**Comment by 0xbaadf00d** [comment]
Hi @marcospereira , any news on your side to review the PR #92 ?

**Comment by 0xbaadf00d** [comment]
Hi @schmitch, it seems that you take the lead on the repo. Do you prefer in first time release new plugin with last 7.x Ebean version and later with last 8.x version or using directly the last 8.x Ebean version ?

Actually we are using these two versions (Ebean 8.2.3 and Ebean 7.21.2) without any issue. It just complicated to tell to our developpers (internal and external) to clone a repo and publishLocal because we are waiting a review.

**Comment by schmitch** [comment]
Actually if you would mac a PR with 8.x I would prefer that.
Actually I didn't take the lead, but I can merge PR's.

If we have a working version we can probably release a new version.

**Comment by 0xbaadf00d** [comment]
Ok, thanks, the PR is ready (#91). If dont want keep WIP commits you can choose "squash and merge" on Github interface.

**Comment by 0xbaadf00d** [comment]
I think this issue could is resolved
